table inet rugov_block {
    set blacklist_v4 {
        type ipv4_addr
        flags interval
    }
    set blacklist_v6 {
        type ipv6_addr
        flags interval
    }
    chain prerouting {
        type filter hook prerouting priority -10; policy accept;
        ip saddr @blacklist_v4 drop
        ip6 saddr @blacklist_v6 drop
    }
}